version: "3.9"
services:
  client:
    build: ./client
    container_name: CLIENT_KERIL
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:5000/
    ports:
      - 5001:80
    volumes:
      - ./client/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  server:
    build: ./server
    container_name: SERVER_KERIL
    environment:
      - PORT=5000
      - DB_NAME=db-store
      - DB_USER=postgres
      - DB_PASSWORD=2308
      - DB_HOST=postgres
      - DB_PORT=5432
      - SECRET_KEY=hfk5odkk4l5fkl4
    ports:
      - 5002:5000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:14
    container_name: DB_KERIL
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "db-store", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2308
      - POSTGRES_DB=db-store
    volumes:
      - ./server/db/init:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
  client_node:
    build:
      context: ./client
      dockerfile:  ./Dockerfile_npm
    container_name: CLIENT_NPM_KERIL
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:5000/
    ports:
      - 5006:3000
volumes:
  postgres: