
version: "3.9"
services:
  postgresDB:
    image: postgres
    container_name: DB_KERIL
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "db-store", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2308
      - POSTGRES_DB=db-store
    volumes:
      - ./server/db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432